### ISSUE TITLE
How to pass a schema to a new ProseMirrorUnified ?

### ISSUE THREAD

**Issue by ManUtopiK** [marekdedic/prosemirror-unified#192]
Hi!

I made some experiments with this package, it looks great.
But after tried to integrate with tiptap, blocknote or proseKit, it looks like it's not really usefull to get the `schema`, the `inputRulesPlugin()` and the `keymapPlugin()` from `pmu` because all of those editors are built on top of prosemirror and provide an API to create the schema and plugins.

In fact, I would like to provide a schema coming from those editors when I instantiate a `new ProseMirrorUnified`.
What I would like to do is to transform markdown input to `prosemirror` schema with remark plugins. Just that.

I wonder how to do ? Maybe I missed something ?

**Comment by ManUtopiK** [comment]
Up!
Anyone read my issue ?

**Comment by marekdedic** [comment]
Read, but had no time to look into it - it's open source, so :shrug: 

I don't really understand TipTap, but it looks like it creates it's own schema for the editor, which, based on their [docs](https://tiptap.dev/docs/editor/guide/output#not-an-option-markdown), is not compatible with Markdown for example.

prosemirror-unified is designed so that you add your own extensions to it. In these extensions, you can add whatever you want to the schema. Maybe you could create an extension that adds the TipTap schema to pmu, but I don't know how that would work. And you would have to support all of the schema yourself...

What is you use-case? If you want to do Markdown with TipTap, pmu and prosemirror-remark, that simply won't work - TipTap schema seems incompatible with markdown. If it's something else, I can't help you much more without knowing the intendend use case...
