### ISSUE TITLE
Integrating a crdt

### ISSUE THREAD

**Issue by av8ta** [marekdedic/prosemirror-unified#221]
Hey nice project! Have you considered where someone hook in to implement collaborative features with a crdt? In the `dispatchTransaction` method maybe? Or perhaps as an extension? I like the idea of having the canonical representation of document state be the unist tree with the crdt managing the tree for replication. Does that make sense for this library?

**Comment by marekdedic** [comment]
Hi, I am not really well-versed in CRDTs, but my thoughts:
- CRDTs are out of sope ot this package - the package is just a bridge between the worlds of ProseMirror and Unified.
- Your idea of having the unist tree be the "canonical representation" sound right to me.
- At the same time, I can't find any CRDT implementation for unist, probably because unist isn't directly meant for editors, where CRDTs are the most useful
- Given that ProseMirror supports collaborative editing with CRDTs, I would just go with that instead...
